// Make the Android plugin available to your modules
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Match this version to your Android Studio / Gradle Plugin version
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

// Allow your app module to fetch libraries from these repos:
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// (Optional) A convenience clean task
task clean(type: Delete) {
    delete rootProject.buildDir
}
